/*  ID is the question number. FIRST is the first part of the question
    before a name will be inserted. SECOND is the remaining part. 

    For example:
    {id: 3, first: "What is ", second: "'s favorite food?"},

    On screen it would display: What is Parshva's favorite food?

    @Important: notice the spacing in first and second. Gear the spacing
    according to the question. Also notice the comma at the end. Add
    it please. 
*/
questions = [
    {id: 1, first: "What is ", second: "'s favorite food?"},
    {id: 2, first: "What is the last youtube video ", second: " watched?"},
    {id: 3, first: "What is ", second: "'s idea of having fun?"},
    {id: 4, first: "If ", second: " won a million dollars, what is the first thing they will buy?"},
    {id: 5, first: "What would ", second: " hide in a shoebox?"},
    {id: 6, first: "If ", second: " could hoard one object, what would it be?"},
    {id: 7, first: "If ", second: " had to change his name, what would he change it to?"},
    {id: 8, first: "What is some irrelevant thing ", second: " always brags about?"},
    {id: 9, first: "What is ", second: "'s idea of a first date?"},
    {id: 10, first: "What is ", second: "'s worst habit?"},
    {id: 11, first: "What will ", second: " be doing when they are 80 years old?"},
    {id: 13, first: "What is ", second: "'s secret talent?"},
    {id: 14, first: "What is the strangest thing ", second: " would buy on amazon?"},
    {id: 15, first: "What is the last thing ", second: " googled?"},
    {id: 16, first: "If ", second: " made a viral youtube video, what would it be about?"},
    {id: 17, first: "What is the first thing ", second: " picks to wear from their wardrobe?"},
    {id: 18, first: "If there is a zombie apocalypse, what would ", second: "'s role be?"},
    {id: 19, first: "If ", second: " ever got into a fist fight, what would be their reason to fight?"},
    {id: 20, first: "If ", second: " only ate one food for the rest of their life, what would it be?"},
    {id: 21, first: "What is ", second: "'s go to pick up line?"},
    {id: 22, first: "What would ", second: " put in their bio on a dating app?"},
    {id: 23, first: "If ", second: " could turn back time, what would they change?"},
    {id: 24, first: "Name a strange skill that ", second: " might have on their resume"},
    {id: 25, first: "If ", second: " became a rapper, what would there stage name be?"},
    {id: 26, first: "If ", second: " were an animal, what would they be?"},
    {id: 27, first: "If ", second: " had a super power, what would it be?"},
    {id: 28, first: "If ", second: " became famous, what would it be for?"},
    {id: 29, first: "If ", second: " won an award, what would it be for?"},
    {id: 30, first: "", second: " spends too much time thinking about..."},
    {id: 31, first: "If ", second: "'s home was burning down and they could choose to save one thing, what would it be? "},
    {id: 32, first: "Describe ", second: " in 3 words"},
    {id: 33, first: "If ", second: " had a guilty obsession, what would it be?"},
    {id: 34, first: "", second: " was detained by the police, what crime did they commit?"},
    {id: 35, first: "If ", second: " had a fear of something, what would it be?"},
    {id: 36, first: "If ", second: " had a catch phrase, what would it be?"},
    {id: 37, first: "What job would ", second: " be terrible at?"},
    {id: 38, first: "What's the dumbest thing that ", second: " has ever done?"},
    {id: 39, first: "", second: " comes home from a stressful day at work, what do they do to relax?"},
    {id: 40, first: "", second: " has just been caught up in a press worthy scandal, what did they do?"},
    {id: 41, first: "If ", second: " had a dance move named after them, what would it be called?"},
    {id: 42, first: "", second: " just wrote a song, what's it called?"},
    {id: 43, first: "", second: " just won the nobel prize for researching something, what is it?"},
    {id: 44, first: "What's the last song that ", second: " listened to?"},
    {id: 45, first: "What is the easiest way to get ", second: " angry?"},
    {id: 46, first: "If ", second: " was a presidential candidate, what would their slogan be?"},
    {id: 47, first: "What is ", second: "'s dream job?"},
    {id: 48, first: "If ", second: " had the chance, what would they stock up in their fridge?"},
    {id: 49, first: "If ", second: " could only say one word for a day, what word would they say?"},
    {id: 50, first: "If ", second: " wasn't playing this game right now, what would they be doing?"},
    {id: 51, first: "", second: " is in a fight. What weapon do they chose?"},
    {id: 53, first: "If ", second: " was stuck in their house the whole day, what would they do?"},
    {id: 54, first: "", second: " is stranded on an island. What is the one object they decided to bring?"},
    {id: 55, first: "What is the strangest food combination you have seen ", second: " combine?"},
    {id: 56, first: "", second: " created a new company. What is the company's name?"},
    {id: 57, first: "", second: " open a restaurant. What do they serve?"},
    {id: 58, first: "What is a bad present to give", second: " for christmas?"},
    {id: 59, first: " ", second: "wants a tattoo! What will they chose?"},
    {id: 60, first: "What pictures would ", second: " post on a dating app?"},
    {id: 61, first: "If you google ", second: "'s name, what would you find?"},
    {id: 62, first: "", second: "is designing a new shoe. What is the brand name?"},
    {id: 63, first: "", second: "is internet famous? What did they do?"},
    {id: 64, first: "If ", second: " was given one wish, what would they wish for?"},
    {id: 65, first: "How would you annoy ", second: "?"},
    {id: 66, first: "Everyone is going on a road trip, but ", second: " realized they forgot something? What was it?"},
    {id: 67, first: "", second: " needs to write an essay on anything they want? What is the topic they will chose?"},
    {id: 68, first: "What is the word or phrase that ", second: " always says?"},
    {id: 69, first: "What is something ", second: " always does that you silently shake your head no to?"},
    {id: 70, first: "What did ", second: " dream about last night?"},
    {id: 71, first: "Give ", second: " a nickname."},
    {id: 72, first: "What does ", second: " want the most?"},
    {id: 73, first: "", second: " got hired for a new job! What is their job?"},
    {id: 74, first: "What does ", second: " daydream about?"},
    {id: 75, first: "You see ", second: " running across the street! Where are they going?"},
    {id: 76, first: "You are at a festival and see ", second: " go on stage with a microphone! What are they about to say?"},
    {id: 77, first: "", second: " adopted a new pet? What is it?"},
    {id: 78, first: "It is time for a potluck! What is ", second: " going to bring?"},
    {id: 79, first: "", second: " needs your help! What do they need you for?"},
    {id: 80, first: "What is ", second: " an expert at?"},
    {id: 81, first: "", second: ""},
    {id: 82, first: "", second: ""},
    {id: 83, first: "", second: ""},
    {id: 84, first: "", second: ""},
    {id: 85, first: "", second: ""},
    {id: 86, first: "", second: ""},
    {id: 87, first: "", second: ""},
    {id: 88, first: "", second: ""},
    {id: 89, first: "", second: ""},
    {id: 90, first: "", second: ""},
    
    


]

question